apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zsgfpa2yf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zsgfpa2yf-go 
  name: zsgfpa2yf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zsgfpa2yf-go 
